config/routes.rb
Rails.application.routes.draw do
  get 'plain_sse', to: 'plain#index'
  get 'progress', to: 'progress#index'
  get 'progress_state', to: 'progress#progress'

  get 'chat', to: 'chat#index'
  post 'chat/send_message/:user', to: 'chat#send_message', as: 'send_message'
  get 'chat/update', to: 'chat#update', as: 'update_chat'
  delete 'chat/reset', to: 'chat#reset', as: 'reset_chat'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
require 'redis'
require 'json'

class Message < ApplicationRecord
  belongs_to :user

  after_commit :notify_new_message, on: :create
  after_destroy :notify_destruction

  private
  def notify_new_message
    # Message.connection.execute "NOTIFY messages, '#{self.id}'"
    $redis.publish 'new_message', self.id
  end

  private
  def notify_destruction
    if Message.count <= 0
      # Message.connection.execute "NOTIFY messages_destroyed"
      $redis.publish 'message_reset', ''
    end
  end

  class << self
    def on_change
      thread = Thread.new do
        Message.connection.execute 'LISTEN messages'
        Message.connection.execute 'LISTEN messages_destroyed'

        loop do
          Message.connection.raw_connection.wait_for_notify do |event, pid, message|
            yield event, message
          end
        end
      end

      thread.join
    ensure
      Thread.kill thread
      Message.connection.execute 'UNLISTEN messages'
      Message.connection.execute 'UNLISTEN messages_destroyed'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages

  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
require "redis"

class ChatController < ApplicationController
  include ActionController::Live

  def index
    if params[:username] && !params[:username].empty?
      user = User.find_by_name(params[:username]);

      if user.nil?
        user = User.create({
          name: params[:username]
        })
      end

      messages = Message.all.order('created_at ASC')
    end

    render locals: {
      user: user || nil,
      messages: messages || nil
    }
  end

  def send_message
    if (params[:content] && !params[:content].empty?)
      user = User.find(params[:user])

      user.messages << Message.create({
        content: params[:content]
      })
    end
  end

  def update
    response.headers['Content-Type'] = 'text/event-stream'
    sse = SSE.new(response.stream)

    user = User.find(params[:user]);

    # Message.on_change do |event, id|
    #   if event == 'messages_destroyed'
    #     sse.write '', event: 'reset'
    #   else
    #     message = Message.find(id)
    #     sse.write({
    #       html: render_to_string(partial: '/chat/message', locals: { message: message, user: user }),
    #       content: message.content,
    #       user: message.user.name,
    #       current_user: user.name
    #     })
    #   end
    # end

    redis = Redis.new
    redis.subscribe ['new_message', 'message_reset', 'heartbeat'] do |on|
      on.message do |channel, data|
        case channel
          when 'new_message'
            message = Message.find(data)
            sse.write ({
              html: render_to_string(partial: '/chat/message', locals: { message: message, user: user }),
              content: message.content,
              user: message.user.name,
              current_user: user.name
            })
          when 'message_reset'
            sse.write '', event: channel
          when 'heartbeat'
            sse.write '', event: 'hb'
        end
      end
    end

    render body: nil
  rescue ClientDisconnected
    # client disconnected
  ensure
    redis.quit
    sse.close if sse
  end

  def reset
    Message.destroy_all

    head :no_content
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/plain_controller.rb
class PlainController < ApplicationController
  include ActionController::Live

  def index
    response.headers['Content-Type'] = 'text/event-stream'
    sse = SSE.new(response.stream)

    begin
      sse.write '', retry: '60000'

      60.times do |i|
        sse.write Time.now.strftime('%c'), event: 'time', id: i

        if Time.now.strftime('%S') == '00'
          sse.write '', event: 'full_minute'
        end

        sleep 1
      end
    ensure
      sse.close
    end

    render body: nil
  end
end

app/controllers/progress_controller.rb
class ProgressController < ApplicationController
  include ActionController::Live

  def index
  end

  def progress
    response.headers['Content-Type'] = 'text/event-stream'
    sse = SSE.new(response.stream)

    1000.times do |i|
      sse.write (i + 1) / 10.0, event: 'progress'
      sleep 0.015
    end

    sse.write '', event: 'stop'
  rescue ClientDisconnected
    logger.info 'Client disconnected'
  ensure
    sse.close
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plain_helper.rb
module PlainHelper
end

app/helpers/progress_helper.rb
module ProgressHelper
end

app/views/chat/_message.slim
.message[class=(message.user == user ? 'own' : '')]
  - if message.user == user
    span.time
      = message.created_at.strftime('%d.%m.%Y %R')
  span.name
    = message.user == user ? 'You' : message.user.name
  - if message.user != user
   span.time
     = message.created_at.strftime('%d.%m.%Y %R')
  p
    = message.content.gsub("\n", '<br>').html_safe

app/views/chat/index.html.slim
.outer
  .inner
    - if user
      .chat
        - messages.each do |message|
          = render 'message', user: user, message: message
      form.chat-form[action=send_message_path(user) method='post']
        input[type="hidden" name="authenticity_token" value=form_authenticity_token]
        textarea[name="content" id="message" autofocus=true]
        button.send-message[type="submit" disabled=true]
          | Send
        button.reset-chat[data-url=reset_chat_path]
          | Reset
      input.update-url[type='hidden' value=update_chat_path(user: user)]
    - else
      form[action="" method="get"]
        label[for="username"]
          | Username
        input[type="text" name="username" id="username" autofocus=true]
        button[type='submit']
          | Begin

app/views/home/index.html.slim
.outer
  .inner
    = link_to 'Plain SSE', plain_sse_path
    = link_to 'Progress', progress_path
    = link_to 'Chat', chat_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SSE Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/progress/index.html.slim
.outer
  .inner
    button.progress-vanilla[data-progress=1 data-path=progress_state_path]
      | Start
    .progress[data-id=1]
      span.percent
        | 0%
      .progress-bar
        .bar-inner
          span.percent.over
            | 0%
    button.progress-jquery[data-progress=2 data-path=progress_state_path]
      | Start
    .progress[data-id=2]
      span.percent
        | 0%
      .progress-bar
        .bar-inner
          span.percent.over
            | 0%